# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c1c8226180a70eb91fcedc0a24c879641c8f801b42c5a12b55cc525a19919bad33d83b438d58563e02a12b107bf00624a323ce73e76a6a3098eec56a1289d6b

test:
  secret_key_base: 2c22382f0ceb2940ca87891609e0dab6e9e71274b9c6156f5f984398c314fa050ff89d7f91526919465348be0616211e4beeeaa6f9cab23381e853b2f6c53a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
